the problems of this nature adapt the equation: y= m1*x1+ m2*x2 + m3*x3 + z
where;
x1,x2 and x3= independent variables(features)
y= dependent variable
m1,m2 and m3= coeficients
b= intercept

In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [2]:
df = pd.read_csv(r'D:\Python\Machine Learning\CSV files\home_prices.csv') #use (r'dir') to access the file
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

to handle the missig values using the median of the other values which returns a decimal value; we use a 'math' model to turn it into a whole value with which we fill all empty slots with fillna() function.

In [3]:
import math
median_bedrooms = math.floor(df.bedrooms.median())
median_bedrooms

3

In [4]:
df.bedrooms = df.bedrooms.fillna(median_bedrooms)
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       3.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [5]:
reg = linear_model.LinearRegression() #creating linear regression object
reg.fit(df[['area', 'bedrooms', 'age']], df.price) #we pass the independent variables and the dependent one(price to train the model

LinearRegression()

In [6]:
reg.coef_  #this gives the coeficients 'm' in price = m1*area+m2*bedrooms+m3*age+b; 'area','bedrooms','age' are features

array([   137.25, -26025.  ,  -6825.  ])

In [7]:
reg.intercept_ #this is b

383725.00000000006

In [8]:
reg.predict([[3000,3,40]]) #the area,bedrooms and age of the home we want to predict

array([444400.])

In [9]:
137.25*3000+-26025*3+-6825*40+383725.00000000006

444400.00000000006

In [10]:
reg.predict([[2500,4,5]])

array([588625.])

In [11]:
import pickle #python module for saving models into a file(it serializes the model into a file)

we open/create a new file called 'model_pickle' using 'with open()
we pass the file name: -model_pickle
we pass wb mode: w-write , b-binary
we then dump the model into the file using 'pickle.dump() and we pass the file 'f'

upon running this a file will be created in the same directory as this notebook.

In [12]:
with open('model_pickle', 'wb') as f:
    pickle.dump(reg,f)
    

we can now use our model to carry out predictions
we open the file in read mode(rb): r-read, b-binary
we load it to the object model(random variable)

In [13]:
with open('model_pickle','rb') as f:
    model=pickle.load(f)

In [14]:
model.predict([[3000,3,40]])

array([444400.])

we can also use joblib module to save a model
joblib is more efficient whenn you have a large number of numpy arrays but it still gives you the same functionality as pickle
joblib can also take the model name correctly

In [16]:
import joblib

In [18]:
joblib.dump(model,'model_joblib')

['model_joblib']

In [19]:
mj=joblib.load('model_joblib')

In [21]:
mj.predict([[3000,3,40]])

array([444400.])

In [23]:
mj.coef_

array([   137.25, -26025.  ,  -6825.  ])